CREATE TABLE `s_f4` (
    `code`                varchar(10)   NOT NULL COMMENT '股票代码',
    `trade_date`          date          NOT NULL COMMENT '交易日期',
    `prev1_trade_date`    date          NULL COMMENT '前1个交易日',
    `prev2_trade_date`    date          NULL COMMENT '前2个交易日',
    `next1_trade_date`    date          NULL COMMENT '后1个交易日',
    `next2_trade_date`    date          NULL COMMENT '后2个交易日',
    `open`                decimal(10,3) NULL COMMENT '开盘价',
    `close`               decimal(10,3) NULL COMMENT '收盘价',
    `high`                decimal(10,3) NULL COMMENT '最高价',
    `low`                 decimal(10,3) NULL COMMENT '最低价',
    `vol`                 bigint        NULL COMMENT '成交量',
    `amount`              bigint        NULL COMMENT '成交额',
    `zx_short_term_trend` decimal(10,3) NULL COMMENT '知行短期趋势',
    `zx_bull_bear_line`   decimal(10,3) NULL COMMENT '知行牛熊线',
    `K`                   decimal(8,3)  NULL COMMENT 'KDJ-K值',
    `D`                   decimal(8,3)  NULL COMMENT 'KDJ-D值',
    `J`                   decimal(8,3)  NULL COMMENT 'KDJ-J值',
    `BBI`                 decimal(10,3) NULL COMMENT 'BBI多空指标',
    `MA5`                 decimal(10,3) NULL COMMENT '5日均线',
    `MA7`                 decimal(10,3) NULL COMMENT '7日均线',
    `MA10`                decimal(10,3) NULL COMMENT '10日均线',
    `MA20`                decimal(10,3) NULL COMMENT '20日均线',
    `MA30`                decimal(10,3) NULL COMMENT '30日均线',
    `MA40`                decimal(10,3) NULL COMMENT '40日均线',
    `MA45`                decimal(10,3) NULL COMMENT '45日均线',
    `MA60`                decimal(10,3) NULL COMMENT '60日均线',
    `MA90`                decimal(10,3) NULL COMMENT '90日均线',
    `MA250`               decimal(10,3) NULL COMMENT '250日均线',
    `DIF`                 decimal(10,4) NULL COMMENT 'MACD-DIF',
    `DEA`                 decimal(10,4) NULL COMMENT 'MACD-DEA',
    `MACD`                decimal(10,4) NULL COMMENT 'MACD柱',
    `zxt`                 decimal(10,3) NULL COMMENT '砖型图信号标志',
    `dzs`                 decimal(10,3) NULL COMMENT '单针短期指标',
    `dzt`                 decimal(10,3) NULL COMMENT '单针长期指标',
    `vol_ratio_0930`      decimal(10,3) NULL COMMENT '9:30量比',
    `vol_ratio_0931`      decimal(10,3) NULL COMMENT '9:31量比',
    `vol_ratio_0932`      decimal(10,3) NULL COMMENT '9:32量比',
    `price_0930`          decimal(10,3) NULL COMMENT '9:30价格',
    `price_0931`          decimal(10,3) NULL COMMENT '9:31价格',
    `price_0932`          decimal(10,3) NULL COMMENT '9:32价格',
    `prev1_close`         decimal(10,3) NULL COMMENT '前1日收盘价',
    `prev1_high`          decimal(10,3) NULL COMMENT '前1日最高价',
    `prev1_low`           decimal(10,3) NULL COMMENT '前1日最低价',
    `prev1_vol`           bigint        NULL COMMENT '前1日成交量',
    `prev2_close`         decimal(10,3) NULL COMMENT '前2日收盘价',
    `prev2_high`          decimal(10,3) NULL COMMENT '前2日最高价',
    `prev2_low`           decimal(10,3) NULL COMMENT '前2日最低价',
    `prev2_vol`           bigint        NULL COMMENT '前2日成交量',
    `prev1_zxt`           decimal(10,3) NULL COMMENT '前1日砖型图信号标志',
    `prev2_zxt`           decimal(10,3) NULL COMMENT '前2日砖型图信号标志',
    `next1_close`         decimal(10,3) NULL COMMENT '后1日收盘价',
    `next1_high`          decimal(10,3) NULL COMMENT '后1日最高价',
    `next1_low`           decimal(10,3) NULL COMMENT '后1日最低价',
    `next1_vol`           bigint        NULL COMMENT '后1日成交量',
    `next2_close`         decimal(10,3) NULL COMMENT '后2日收盘价',
    `next2_high`          decimal(10,3) NULL COMMENT '后2日最高价',
    `next2_low`           decimal(10,3) NULL COMMENT '后2日最低价',
    `next2_vol`           bigint        NULL COMMENT '后2日成交量',
    `prev1_j`             decimal(8,3)  NULL COMMENT '前1日KDJ-J值',
    `prev1_dzt`           decimal(10,3) NULL COMMENT '前1日单针长期指标',
    `prev2_dzt`           decimal(10,3) NULL COMMENT '前2日单针长期指标',
    `prev1_dzs`           decimal(10,3) NULL COMMENT '前1日单针短期指标',
    `prev2_dzs`           decimal(10,3) NULL COMMENT '前2日单针短期指标',
    `prev1_rate`          decimal(8,4)  NULL COMMENT '前1日涨跌幅',
    `next1_rate`          decimal(8,4)  NULL COMMENT '后1日涨跌幅',
    `next1_high_rate`     decimal(8,4)  NULL COMMENT '后1日最高涨幅',
    `today_rate`          decimal(8,4)  NULL COMMENT '当日涨跌幅',
    `double_vol_f`        tinyint(1)    NULL COMMENT '倍量标志(0/1)',
    `zt_f`                tinyint(1)    NULL COMMENT '涨停标志(0/1)',
    `zxt_f`               tinyint(1)    NULL COMMENT '砖型图信号标志(0/1)',
    `b2_f`                tinyint(1)    NULL COMMENT 'B2信号标志(0/1)',
    `double_vol_f_d5`     bigint        NULL COMMENT '近5日倍量标志次数',
    `double_vol_f_d10`    bigint        NULL COMMENT '近10日倍量标志次数',
    `zt_f_d5`             bigint        NULL COMMENT '近5日涨停次数',
    `zt_f_d10`            bigint        NULL COMMENT '近10日涨停次数',
    `b2_f_d5`             bigint        NULL COMMENT '近5日B2信号次数',
    `b2_f_d10`            bigint        NULL COMMENT '近10日B2信号次数'
) ENGINE=OLAP
UNIQUE KEY(`code`, `trade_date`)
DISTRIBUTED BY HASH(`code`) BUCKETS 10
PROPERTIES (
    "replication_allocation" = "tag.location.default: 1",
    "min_load_replica_num" = "-1",
    "is_being_synced" = "false",
    "storage_medium" = "hdd",
    "storage_format" = "V2",
    "inverted_index_storage_format" = "V1",
    "light_schema_change" = "true",
    "disable_auto_compaction" = "false",
    "enable_single_replica_compaction" = "false",
    "compression" = "LZ4",
    "group_commit_interval_ms" = "10000",
    "group_commit_data_bytes" = "134217728"
);
